#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
    totalSum = 0
    min, max = arr[0], arr[0]
    
    # track total, find min and max value
    for i in arr:
        totalSum += i
        if i < min: min = i
        if i > max: max = i
        
    # max and min sum with 4 out of 5 elements:
    print(f"{totalSum - max} {totalSum - min}")

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
