#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    # Write your code here
    lowCount, hiCount = 0, 0
    minRec, hiRec = scores[0], scores[0]
    
    # track number of new high and low records
    for i in scores:
        if i > hiRec:
            hiCount += 1
            hiRec = i
        if i < minRec:
            lowCount += 1
            minRec = i
    return [hiCount, lowCount]
    
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
