#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    pos, neg, zero = 0, 0, 0
    
    # increment counters based on value
    for i in arr:
        if i > 0: pos += 1
        if i < 0: neg += 1
        if i == 0: zero += 1
    # printing proportion of each type of value in array
    print(f"{pos / len(arr):.6f}")
    print(f"{neg / len(arr):.6f}")
    print(f"{zero / len(arr):.6f}")
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
